### ISSUE TITLE
WHATSAPP - Desenvolvimento de ícone.

### ISSUE THREAD

**Issue by TolbyOwl** [EricAngelo22/Projeto-Uninove#12]
Para que os visitantes possam entrar em contato com agilidade será preciso adicionar o ícone de Whatsapp que leve diretamente para o chat com a cliente de forma rápida e prática. Será preciso estar localizado no canto inferior direito e acompanhando locomoção pelo site de maneira responsiva.

**Comment by WiniciusAlencar** [comment]
!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<title>Botão WhatsApp - Doutora</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
	<style>
		.whatsapp-link {
			position: fixed;
			width: 60px;
			height: 60px;
			bottom: 40px;
			right: 40px;
			background-color: #25d366;
			color: #fff;
			border-radius: 50px;
			text-align: center;
			font-size: 30px;
			box-shadow: 1px 1px 2px #888;
			z-index: 1000;
		}
 
		.fa-whatsapp {
			margin-top: 16px;
		}
	</style>
</head>
<body>
	<a class="whatsapp-link" href="https://web.whatsapp.com/send?phone=5519992453104" target="_blank">
		<i class="fa fa-whatsapp"></i>
	</a>
</body>
</html>

**Comment by TolbyOwl** [comment]
Adicionada animação.

```css
   /* Initiate Auto-Pulse animations */
  .whatsapp-link.pulse-button {
  animation: borderPulse 1000ms infinite ease-in-out;
 }

@keyframes borderPulse {
  0% {
    box-shadow: inset 0px 0px 0px 5px rgba(77, 216, 13, 0.664), 0px 0px 0px 0px rgb(18, 162, 2);
  }
  100% {
    box-shadow: inset 0px 0px 0px 3px rgba(117, 117, 255,.2), 0px 0px 0px 10px rgba(255,255,255,0);
  }
}
```
