### ISSUE TITLE
FOOTER - Desenvolver o Footer do site.

### ISSUE THREAD

**Issue by TolbyOwl** [EricAngelo22/Projeto-Uninove#3]
A cliente(Patrícia Braga): "Gostaria que no site houvesse uma sessão onde o usuário poderia ter acesso aos meus meios de contato, e que nele houvesse botões/links de redirecionamento."

Critério de aceite: 
- Meios de contato
- Botões/links que redirecionam ao contato.
- formatação de footer.

Responsável:
-Eric

**Comment by EricAngelo22** [comment]
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footer</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" type="text/css" href="fontawesome-free-6.6.0-web\css\all.min.css">
</head>
<body>
    <script src="dropdown.js"></script>


  <div class="dropdown">

        <ul>
          <li>
            <button onclick="toggleContent()">Atende algum convênio?</button> <div class="conteudo1">
            <p>Os atendimentos são realizados na modalidade particular, os pacientes que possuem plano de saúde podem solicitar o reembolso do valor com o seu plano mediante apresentação do recibo</p>
        </div>
          </li>
          <li><button onclick="toggleContent()">Qual a hora certa de buscar ajuda?</button> <div class="conteudo2">
            <p>Se você está buscando por um psicólogo, provavelmente algo está te incomodando. Alguns sentimentos ruins, que antes apareciam de vez em quando, podem estar presentes mais vezes do que você gostaria.
                Quando os sentimentos começam a atrapalhar o seu cotidiano, é hora de procurar ajuda! Se a ansiedade, a depressão ou a dificuldade para dormir, por exemplo, estão te atrapalhando no trabalho ou nas suas relações, é o momento de começar a cuidar da sua saúde mental e entender as causas e a melhor forma de lidar com esses sentimentos. Não é uma tarefa fácil, e não é possível determinar um tempo para que a melhora comece a aparecer, mas com o decorrer das sessões o paciente percebe os benefícios de estar fazendo psicoterapia. Se você está nesse momento, envie uma mensagem e vamos conversar!</p>
        </div></li>
          <li><button onclick="toggleContent()">Atende crianças?</button> <div class="conteudo3">
            <p>Não, somente adultos.</p>
        </div></li>
          <li><button onclick="toggleContent()">Qual a sua abordagem?</button> <div class="conteudo4">
            <p>Minha escuta terapêutica é baseada na abordagem teórica dos princípios da Análise do comportamento. É feito uma análise dos acontecimentos da vida do paciente/cliente, buscando entender a relação de determinados comportamentos da sua vida que estão causando sofrimento e, a partir disso, planejamos estratégias adequadas que possam favorecer mudanças em sua vida.
                Quanto tempo dura uma sessão?
                As sessões duram 50 minutos, ocorrem com agendamento prévio, geralmente os horários são fixos. </p>
        </div></li>
          <li><button onclick="toggleContent()">Como funciona a consulta online?</button> <div class="conteudo5">
            <p>A sessão online ocorre por chamada de vídeo, agendamos um dia e horário, onde é enviado no dia da sessão um link de uma sala virtual e segura, a pessoa precisa está com uma conexão estável de internet e fazemos a chamada de vídeo,
                Quanto tempo dura o processo terapêutico?
                Não há como sabermos de antemão por quanto tempo durará um processo terapêutico, depende da necessidade do caso, mas as mudanças comportamentais vão sendo percebida nos primeiros meses.</p>
        </div></li>
          <li><button onclick="toggleContent()">Quais as formas de pagamento?</button> <div class="conteudo6">
            <p>O pagamento é realizado por pix ou link de pagamento online no débito ou crédito.</p>
        </div></li>
        </ul>

    </div>



    <!--Caixa de Texto endereço e contato -->
    <ul class="endereco_contat">

        <li class="ajudar">
            <h1>Estou aqui para te ajudar!</h1>
            <p>A psicoterapia pode ajudá-lo a alcançar uma vida mais satisfatória, ensinando-lhe estratégias para lidar com os desafios da vida.</p>
            <hr>
        

        <div class="endereco">
            <h1>Campinas, SP</h1>
            <p>Rua Olímpia, 5 Chácara da Barra -- Campinas</p>
            <p>psipatriciabraga@gmail.com</p>
            <p>+55 19 99245-3104</p>

        </li>

        <div class="atendimento">
            <h1>ATENDIMENTO</h1>
            <h2>ONLINE E PRESENCIAL</h2>
            <h3>Dúvidas</h3>
            <p>Entre em Contato</p>
            <div>
            <button>
                <a href="https://l.instagram.com/?u=https%3A%2F%2Fbit.ly%2Fcontatopatriciapsicologa&e=AT3wpJ9VPHf9XIW0Y5lEqRzsWi884rFxunBS1z32kVBKR7VsRMNgg6LQU7PJWTHlS3wsLDWq6EMPkbexIY2e_ytweN21SCmE46-pPg">
                 <h2> <i class="fa-brands fa-whatsapp"> </i> Agendar Consulta  </h2>
                </a>
              </button>
            </div>
            <p>Segunda à sexta 10:00 às 19:00</p>

        </div>

    </ul>

    <!--Footer-->

    <footer>

        <div class="boxs">
            <h2>Inicio</h2>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Psicologa clinica</a></li>
                <li><a href="#">Área</a></li>
            </ul>

        </div>

        <div class="boxs">
            <h2>Informações</h2>
            <ul>
                <li><a href="#">Localização</a></li>
                <li><a href="#">Contato</a></li>
                <li><a href="#">E-mail</a></li>
            </ul>

        </div>

        <div class="boxs">
            <h2>Suporte</h2>
            <ul>
                <li><a href="#">FAQ</a></li>
                <li><a href="#">Telefone</a></li>
                <li><a href="#">Whatsapp</a></li>
            </ul>

        </div>

        <div class="boxs">
            <h2>Sobre nós</h2>
            <p>

                Atendimento para adolescentes e adultos, fundamentada com a abordagem teórica análise do comportamento.
            </p>

    

        </div>

    </footer>

    <div class="copyright">
        &copy; 2024 Patricia Braga. Todos os direitos reservados.
      </div>

    
</body>
</html>
``` 


```css
.dropdown button {
    color: #8C5716;
    background: #f8c186;
    border: none;
    cursor: pointer;
}

.dropdown p {
    color: #A67E4E;
    text-decoration: none;
}

.dropdown .conteudo1{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}

.dropdown .conteudo2{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}
.dropdown .conteudo3{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}
.dropdown .conteudo4{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}

.dropdown .conteudo5{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}

.dropdown .conteudo6{
    background: white;
    box-shadow: 2px 2px 5px;
    display: none;
}



.nav {
    justify-content: right;
  }



.conteudo
{
    width: 100%;
    height: 50vh;
    display: flex;
    justify-content: center;
    align-items: center;
}

.conteudo h1
{
    font-size: 15vw;
    text-transform: uppercase;
}

footer
{
    width: 100%;
    min-height: 250px;
    background: #F2DFDF;
    display: flex;
    margin: 0;
    padding: 0;
    font-family: sans-serif;
    box-sizing: border-box;
    
}

footer .boxs
{

    width: 320px;
    min-height: 150px;
    padding: 20px;
}

footer .boxs:nth-child(4)
{
    width:400px
}

.boxs h2
{
    color:#874E3A;
    margin-bottom: 20px;
    text-decoration: underline;

}

.boxs ul li
{
    margin:10px 0px;
    list-style: none;
}

.boxs ul li a
{
    color: #874E3A;
    text-decoration: none;
}

.boxs ul li a:hover
{
    color: #874E3A;
}

.boxs p
{
    color: #874E3A;
    text-align: justify;
}



.endereco_contat
{
    display: flex;
    gap: 50px;
    margin-bottom: 20px;
    flex-direction: row;
    list-style: none;
    justify-content: center;

}



.endereco_contat h1
{
    color: #8C5716;
}

.endereco_contat p
{
    color: #A67E4E;
}

.endereco_contat h2
{
    color: #A67E4E;
}

.endereco_contat h3
{
    color: #A67E4E;
}

.atendimento
{
   background-color: #F2DFDF;
   text-align: center;
   border-radius: 10px;
   width: 350px;
}

.copyright
{
    text-align: center;
}

.button h2
{
    text-decoration: none;
    display: flex;
    font-size: 2em;
}

.button i
{
    font-size: 2em;
}







@media(max-width: 950px)
{
    .endereco_contat
    {
        flex-direction: column;
        width: 100%;
        text-align: center;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    footer
    {
        flex-direction: column;
    }
    footer .boxs
    {
        width: 100%;
        text-align: center;
    }
    footer .boxs:nth-child(4) 
    {
    width: 100%
    }
}
``` 

```javascript
function toggleContent() {
    var content = document.querySelector('.dropdown .conteudo1');
    if (content.style.display === 'block') {
        content.style.display = 'none';
    } else {
        content.style.display = 'block';
    }
}

```
